# SPDX-FileCopyrightText: 2022 nerdyscout <https://github.com/nerdyscout/>
#
# SPDX-License-Identifier: CC0-1.0

name: PlatformIO

on:
  workflow_dispatch:
  push:
    paths:
    - src/**
    - lib/**
    - test/**
  pull_request:
    paths:
    - src/**
    - lib/**
    - test/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
# https://github.com/karniv00l/platformio-run-action
      - uses: karniv00l/platformio-run-action@0.1.0
#        with:
#          environments: ""
#          targets: ""
#          jobs: 6
#          silent: false
#          verbose: true
#          disable-auto-clean: false